#  to use  multi containers and make diff things
version: "3.8"
services:
  db:
    image: redis
    volumes:
      - #- our host maschine: our container


  
  web:
    build: .
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine"


  '''
Web service
The web service uses an image that’s built from the Dockerfile in the current directory. 
It then binds the container and the host machine to the exposed port, 8000. 
This example service uses the default port for the Flask web server, 5000.

Redis service
The redis service uses a public Redis image pulled from the Docker Hub registry.
  '''